---
- name: Full system upgrade
  include: system_upgrade.yml
  become: true

- name: Install usual apps
  include: install_usual_apps.yml
  become: true

- name: Create ansible user
  user: name={{ ansib_user }} system=yes
  become: true

- name: Special sudo for ansible
  debug: msg="Do something here when security is enough"
  become: true

- name: Create my private user
  user: name={{ my_pvt_user }} shell=/usr/bin/zsh
  become: true

- name: Include user to common groups
  include: tools/add2groups.yml user={{ my_pvt_user }} isadm=1
  become: true

# Pvt user config
- name: Install Oh My Zsh
  git: 
    repo: https://github.com/robbyrussell/oh-my-zsh.git
    dest: ~/.oh-my-zsh
- name: Install my conf files for my pvt user
  git:
    repo: ssh://git@github.com/cpenar/conffiles.git
    dest: ~/work/conffiles
    key_file: ~/.ssh/id_rsa
- name: Install Vundle
  git:
    repo: https://github.com/VundleVim/Vundle.vim.git
    dest: ~/.vim/bundle/Vundle.vim

- name: Link my conffiles
  include: tools/linkfile.yml src="{{ item.src }}" dest="{{ item.dest }}"
  with_items:
     - { src: '/home/cpenar/work/conffiles/.zshrc', dest: '/home/cpenar/.zshrc'}
     - { src: '/home/cpenar/work/conffiles/.vimrc_ultisnip', dest: '/home/cpenar/.vimrc' }
     - { src: '/home/cpenar/work/conffiles/.i3_config', dest: '/home/cpenar/.i3/config' }
     - { src: '/home/cpenar/work/conffiles/.gitconfig', dest: '/home/cpenar/.gitconfig' }
