---
- name: Do a full Archlinux system upgrade
  when: ansible_os_family == 'Archlinux'
  pacman: update_cache=yes upgrade=yes

- name: Do a full Debian system dist-upgrade
  when: ansible_os_family == 'Debian'
  apt: update_cache=yes upgrade=dist


